import Floor from "./Floor";
import {useState} from "react";
import Building from "./Building";
import {Col, Row} from "antd";
import '../css/main.scss';

function Main() {
    const [floor, setFloor] = useState(0);
    const [room, setRoom] = useState({});

    const buildingModel = [
        {
            id: 'floor1', corridor: [
                {
                    id: 'f1-c1', rooms: [
                        {id: 'f1-c1-r1', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c1-r2', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c1-r3', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c1-r4', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c1-r5', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c1-r6', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c1-r7', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c1-r8', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c1-r9', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c1-r10', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c1-r11', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c1-r12', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c1-r13', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c1-r14', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c1-r15', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c1-r16', isEmpty: false, capacity: '3', full: false}
                    ]
                },
                {
                    id: 'f1-c2', rooms: [
                        {id: 'f1-c2-r1', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c2-r2', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c2-r3', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c2-r4', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c2-r5', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c2-r6', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c2-r7', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c2-r8', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c2-r9', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c2-r10', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c2-r11', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c2-r12', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c2-r13', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c2-r14', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c2-r15', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c2-r16', isEmpty: false, capacity: '3', full: false}
                    ]
                },
                {
                    id: 'f1-c3', rooms: [
                        {id: 'f1-c3-r1', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c3-r2', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c3-r3', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c3-r4', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c3-r5', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c3-r6', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c3-r7', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c3-r8', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c3-r9', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c3-r10', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c3-r11', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c3-r12', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c3-r13', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c3-r14', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c3-r15', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c3-r16', isEmpty: false, capacity: '3', full: false}
                    ]
                },
                {
                    id: 'f1-c4', rooms: [
                        {id: 'f1-c4-r1', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c4-r2', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c4-r3', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c4-r4', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c4-r5', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c4-r6', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c4-r7', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c4-r8', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c4-r9', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c4-r10', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c4-r11', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c4-r12', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c4-r13', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c4-r14', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c4-r15', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c4-r16', isEmpty: false, capacity: '3', full: false}
                    ]
                },
                {
                    id: 'f1-c5', rooms: [
                        {id: 'f1-c5-r1', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c5-r2', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c5-r3', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c5-r4', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c5-r5', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c5-r6', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c5-r7', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c5-r8', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c5-r9', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c5-r10', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c5-r11', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c5-r12', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c5-r13', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c5-r14', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c5-r15', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c5-r16', isEmpty: false, capacity: '3', full: false}
                    ]
                },
                {
                    id: 'f1-c6', rooms: [
                        {id: 'f1-c6-r1', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c6-r2', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c6-r3', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c6-r4', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c6-r5', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c6-r6', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c6-r7', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c6-r8', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c6-r9', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c6-r10', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c6-r11', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c6-r12', isEmpty: true, capacity: '3', full: false},
                        {id: 'f1-c6-r13', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c6-r14', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c6-r15', isEmpty: false, capacity: '3', full: false},
                        {id: 'f1-c6-r16', isEmpty: false, capacity: '3', full: false}
                    ]
                }
            ]
        },
        {
            id: 'floor2', corridor: [
                {
                    id: 'f2-c1', rooms: [
                        {id: 'f2-c1-r1', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c1-r2', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c1-r3', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c1-r4', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c1-r5', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c1-r6', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c1-r7', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c1-r8', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c1-r9', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c1-r10', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c1-r11', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c1-r12', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c1-r13', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c1-r14', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c1-r15', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c1-r16', isEmpty: false, capacity: '3', full: false}
                    ]
                },
                {
                    id: 'f2-c2', rooms: [
                        {id: 'f2-c2-r1', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c2-r2', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c2-r3', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c2-r4', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c2-r5', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c2-r6', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c2-r7', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c2-r8', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c2-r9', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c2-r10', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c2-r11', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c2-r12', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c2-r13', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c2-r14', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c2-r15', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c2-r16', isEmpty: false, capacity: '3', full: false}
                    ]
                },
                {
                    id: 'f2-c3', rooms: [
                        {id: 'f2-c3-r1', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c3-r2', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c3-r3', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c3-r4', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c3-r5', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c3-r6', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c3-r7', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c3-r8', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c3-r9', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c3-r10', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c3-r11', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c3-r12', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c3-r13', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c3-r14', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c3-r15', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c3-r16', isEmpty: false, capacity: '3', full: false}
                    ]
                },
                {
                    id: 'f2-c4', rooms: [
                        {id: 'f2-c4-r1', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c4-r2', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c4-r3', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c4-r4', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c4-r5', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c4-r6', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c4-r7', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c4-r8', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c4-r9', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c4-r10', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c4-r11', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c4-r12', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c4-r13', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c4-r14', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c4-r15', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c4-r16', isEmpty: false, capacity: '3', full: false}
                    ]
                },
                {
                    id: 'f2-c5', rooms: [
                        {id: 'f2-c5-r1', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c5-r2', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c5-r3', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c5-r4', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c5-r5', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c5-r6', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c5-r7', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c5-r8', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c5-r9', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c5-r10', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c5-r11', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c5-r12', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c5-r13', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c5-r14', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c5-r15', isEmpty: true, capacity: '3', full: false},
                        {id: 'f2-c5-r16', isEmpty: false, capacity: '3', full: false}
                    ]
                },
                {
                    id: 'f2-c6', rooms: [
                        {id: 'f2-c6-r1', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c6-r2', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c6-r3', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c6-r4', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c6-r5', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c6-r6', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c6-r7', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c6-r8', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c6-r9', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c6-r10', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c6-r11', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c6-r12', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c6-r13', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c6-r14', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c6-r15', isEmpty: false, capacity: '3', full: false},
                        {id: 'f2-c6-r16', isEmpty: false, capacity: '3', full: false}
                    ]
                }
            ]
        },
    ];

    const rooms = [
        {id: 'f1-c1-r1', users: [], type: [], name: [], infos: []},
        {id: 'f1-c1-r2', users: [], type: [], name: [], infos: []},
        {id: 'f1-c1-r3', users: [], type: [], name: [], infos: []},
        {id: 'f1-c1-r4', users: [], type: [], name: [], infos: []},
        {id: 'f1-c1-r5', users: [], type: [], name: [], infos: []},
        {id: 'f1-c1-r6', users: [], type: [], name: [], infos: []},
        {id: 'f1-c1-r7', users: [], type: [], name: [], infos: []},
        {id: 'f1-c1-r8', users: [], type: [], name: [], infos: []},
        {id: 'f1-c1-r9', users: [], type: [], name: [], infos: []},
        {id: 'f1-c1-r10', users: [], type: [], name: [], infos: []},
        {id: 'f1-c1-r11', users: [], type: [], name: [], infos: []},
        {id: 'f1-c1-r12', users: [], type: [], name: [], infos: []},
        {id: 'f1-c1-r13', users: [], type: [], name: [], infos: []},
        {id: 'f1-c1-r15', users: [], type: [], name: [], infos: []},
        {id: 'f1-c1-r16', users: [], type: [], name: [], infos: []},
        {id: 'f1-c2-r1', users: [], type: [], name: [], infos: []},
        {id: 'f1-c2-r2', users: [], type: [], name: [], infos: []},
        {id: 'f1-c2-r3', users: [], type: [], name: [], infos: []},
        {id: 'f1-c2-r4', users: [], type: [], name: [], infos: []},
        {id: 'f1-c2-r5', users: [], type: [], name: [], infos: []},
        {id: 'f1-c2-r6', users: [], type: [], name: [], infos: []},
        {id: 'f1-c2-r7', users: [], type: [], name: [], infos: []},
        {id: 'f1-c2-r8', users: [], type: [], name: [], infos: []},
        {id: 'f1-c2-r9', users: [], type: [], name: [], infos: []},
        {id: 'f1-c2-r10', users: [], type: [], name: [], infos: []},
        {id: 'f1-c2-r11', users: [], type: [], name: [], infos: []},
        {id: 'f1-c2-r12', users: [], type: [], name: [], infos: []},
        {id: 'f1-c2-r13', users: [], type: [], name: [], infos: []},
        {id: 'f1-c2-r15', users: [], type: [], name: [], infos: []},
        {id: 'f1-c2-r16', users: [], type: [], name: [], infos: []},
        {id: 'f1-c3-r1', users: [], type: [], name: [], infos: []},
        {id: 'f1-c3-r2', users: [], type: [], name: [], infos: []},
        {id: 'f1-c3-r3', users: [], type: [], name: [], infos: []},
        {id: 'f1-c3-r4', users: [], type: [], name: [], infos: []},
        {id: 'f1-c3-r5', users: [], type: [], name: [], infos: []},
        {id: 'f1-c3-r6', users: [], type: [], name: [], infos: []},
        {id: 'f1-c3-r7', users: [], type: [], name: [], infos: []},
        {id: 'f1-c3-r8', users: [], type: [], name: [], infos: []},
        {id: 'f1-c3-r9', users: [], type: [], name: [], infos: []},
        {id: 'f1-c3-r10', users: [], type: [], name: [], infos: []},
        {id: 'f1-c3-r11', users: [], type: [], name: [], infos: []},
        {id: 'f1-c3-r12', users: [], type: [], name: [], infos: []},
        {id: 'f1-c3-r13', users: [], type: [], name: [], infos: []},
        {id: 'f1-c3-r15', users: [], type: [], name: [], infos: []},
        {id: 'f1-c3-r16', users: [], type: [], name: [], infos: []},
        {id: 'f1-c4-r1', users: [], type: [], name: [], infos: []},
        {id: 'f1-c4-r2', users: [], type: [], name: [], infos: []},
        {id: 'f1-c4-r3', users: [], type: [], name: [], infos: []},
        {id: 'f1-c4-r4', users: [], type: [], name: [], infos: []},
        {id: 'f1-c4-r5', users: [], type: [], name: [], infos: []},
        {id: 'f1-c4-r6', users: [], type: [], name: [], infos: []},
        {id: 'f1-c4-r7', users: [], type: [], name: [], infos: []},
        {id: 'f1-c4-r8', users: [], type: [], name: [], infos: []},
        {id: 'f1-c4-r9', users: [], type: [], name: [], infos: []},
        {id: 'f1-c4-r10', users: [], type: [], name: [], infos: []},
        {id: 'f1-c4-r11', users: [], type: [], name: [], infos: []},
        {id: 'f1-c4-r12', users: [], type: [], name: [], infos: []},
        {id: 'f1-c4-r13', users: [], type: [], name: [], infos: []},
        {id: 'f1-c4-r15', users: [], type: [], name: [], infos: []},
        {id: 'f1-c4-r16', users: [], type: [], name: [], infos: []},
        {id: 'f1-c5-r1', users: [], type: [], name: [], infos: []},
        {id: 'f1-c5-r2', users: [], type: [], name: [], infos: []},
        {id: 'f1-c5-r3', users: [], type: [], name: [], infos: []},
        {id: 'f1-c5-r4', users: [], type: [], name: [], infos: []},
        {id: 'f1-c5-r5', users: [], type: [], name: [], infos: []},
        {id: 'f1-c5-r6', users: [], type: [], name: [], infos: []},
        {id: 'f1-c5-r7', users: [], type: [], name: [], infos: []},
        {id: 'f1-c5-r8', users: [], type: [], name: [], infos: []},
        {id: 'f1-c5-r9', users: [], type: [], name: [], infos: []},
        {id: 'f1-c5-r10', users: [], type: [], name: [], infos: []},
        {id: 'f1-c5-r11', users: [], type: [], name: [], infos: []},
        {id: 'f1-c5-r12', users: [], type: [], name: [], infos: []},
        {id: 'f1-c5-r13', users: [], type: [], name: [], infos: []},
        {id: 'f1-c5-r15', users: [], type: [], name: [], infos: []},
        {id: 'f1-c5-r16', users: [], type: [], name: [], infos: []},
        {id: 'f1-c6-r1', users: [], type: [], name: [], infos: []},
        {id: 'f1-c6-r2', users: [], type: [], name: [], infos: []},
        {id: 'f1-c6-r3', users: [], type: [], name: [], infos: []},
        {id: 'f1-c6-r4', users: [], type: [], name: [], infos: []},
        {id: 'f1-c6-r5', users: [], type: [], name: [], infos: []},
        {id: 'f1-c6-r6', users: [], type: [], name: [], infos: []},
        {id: 'f1-c6-r7', users: [], type: [], name: [], infos: []},
        {id: 'f1-c6-r8', users: [], type: [], name: [], infos: []},
        {id: 'f1-c6-r9', users: [], type: [], name: [], infos: []},
        {id: 'f1-c6-r10', users: [], type: [], name: [], infos: []},
        {id: 'f1-c6-r11', users: [], type: [], name: [], infos: []},
        {id: 'f1-c6-r12', users: [], type: [], name: [], infos: []},
        {id: 'f1-c6-r13', users: [], type: [], name: [], infos: []},
        {id: 'f1-c6-r15', users: [], type: [], name: [], infos: []},
        {id: 'f1-c6-r16', users: [], type: [], name: [], infos: []},
        {id: 'f2-c1-r1', users: [], type: [], name: [], infos: []},
        {id: 'f2-c1-r2', users: [], type: [], name: [], infos: []},
        {id: 'f2-c1-r3', users: [], type: [], name: [], infos: []},
        {id: 'f2-c1-r4', users: [], type: [], name: [], infos: []},
        {id: 'f2-c1-r5', users: [], type: [], name: [], infos: []},
        {id: 'f2-c1-r6', users: [], type: [], name: [], infos: []},
        {id: 'f2-c1-r7', users: [], type: [], name: [], infos: []},
        {id: 'f2-c1-r8', users: [], type: [], name: [], infos: []},
        {id: 'f2-c1-r9', users: [], type: [], name: [], infos: []},
        {id: 'f2-c1-r10', users: [], type: [], name: [], infos: []},
        {id: 'f2-c1-r11', users: [], type: [], name: [], infos: []},
        {id: 'f2-c1-r12', users: [], type: [], name: [], infos: []},
        {id: 'f2-c1-r13', users: [], type: [], name: [], infos: []},
        {id: 'f2-c1-r15', users: [], type: [], name: [], infos: []},
        {id: 'f2-c1-r16', users: [], type: [], name: [], infos: []},
        {id: 'f2-c2-r1', users: [], type: [], name: [], infos: []},
        {id: 'f2-c2-r2', users: [], type: [], name: [], infos: []},
        {id: 'f2-c2-r3', users: [], type: [], name: [], infos: []},
        {id: 'f2-c2-r4', users: [], type: [], name: [], infos: []},
        {id: 'f2-c2-r5', users: [], type: [], name: [], infos: []},
        {id: 'f2-c2-r6', users: [], type: [], name: [], infos: []},
        {id: 'f2-c2-r7', users: [], type: [], name: [], infos: []},
        {id: 'f2-c2-r8', users: [], type: [], name: [], infos: []},
        {id: 'f2-c2-r9', users: [], type: [], name: [], infos: []},
        {id: 'f2-c2-r10', users: [], type: [], name: [], infos: []},
        {id: 'f2-c2-r11', users: [], type: [], name: [], infos: []},
        {id: 'f2-c2-r12', users: [], type: [], name: [], infos: []},
        {id: 'f2-c2-r13', users: [], type: [], name: [], infos: []},
        {id: 'f2-c2-r15', users: [], type: [], name: [], infos: []},
        {id: 'f2-c2-r16', users: [], type: [], name: [], infos: []},
        {id: 'f2-c3-r1', users: [], type: [], name: [], infos: []},
        {id: 'f2-c3-r2', users: [], type: [], name: [], infos: []},
        {id: 'f2-c3-r3', users: [], type: [], name: [], infos: []},
        {id: 'f2-c3-r4', users: [], type: [], name: [], infos: []},
        {id: 'f2-c3-r5', users: [], type: [], name: [], infos: []},
        {id: 'f2-c3-r6', users: [], type: [], name: [], infos: []},
        {id: 'f2-c3-r7', users: [], type: [], name: [], infos: []},
        {id: 'f2-c3-r8', users: [], type: [], name: [], infos: []},
        {id: 'f2-c3-r9', users: [], type: [], name: [], infos: []},
        {id: 'f2-c3-r10', users: [], type: [], name: [], infos: []},
        {id: 'f2-c3-r11', users: [], type: [], name: [], infos: []},
        {id: 'f2-c3-r12', users: [], type: [], name: [], infos: []},
        {id: 'f2-c3-r13', users: [], type: [], name: [], infos: []},
        {id: 'f2-c3-r15', users: [], type: [], name: [], infos: []},
        {id: 'f2-c3-r16', users: [], type: [], name: [], infos: []},
        {id: 'f2-c4-r1', users: [], type: [], name: [], infos: []},
        {id: 'f2-c4-r2', users: [], type: [], name: [], infos: []},
        {id: 'f2-c4-r3', users: [], type: [], name: [], infos: []},
        {id: 'f2-c4-r4', users: [], type: [], name: [], infos: []},
        {id: 'f2-c4-r5', users: [], type: [], name: [], infos: []},
        {id: 'f2-c4-r6', users: [], type: [], name: [], infos: []},
        {id: 'f2-c4-r7', users: [], type: [], name: [], infos: []},
        {id: 'f2-c4-r8', users: [], type: [], name: [], infos: []},
        {id: 'f2-c4-r9', users: [], type: [], name: [], infos: []},
        {id: 'f2-c4-r10', users: [], type: [], name: [], infos: []},
        {id: 'f2-c4-r11', users: [], type: [], name: [], infos: []},
        {id: 'f2-c4-r12', users: [], type: [], name: [], infos: []},
        {id: 'f2-c4-r13', users: [], type: [], name: [], infos: []},
        {id: 'f2-c4-r15', users: [], type: [], name: [], infos: []},
        {id: 'f2-c4-r16', users: [], type: [], name: [], infos: []},
        {id: 'f2-c5-r1', users: [], type: [], name: [], infos: []},
        {id: 'f2-c5-r2', users: [], type: [], name: [], infos: []},
        {id: 'f2-c5-r3', users: [], type: [], name: [], infos: []},
        {id: 'f2-c5-r4', users: [], type: [], name: [], infos: []},
        {id: 'f2-c5-r5', users: [], type: [], name: [], infos: []},
        {id: 'f2-c5-r6', users: [], type: [], name: [], infos: []},
        {id: 'f2-c5-r7', users: [], type: [], name: [], infos: []},
        {id: 'f2-c5-r8', users: [], type: [], name: [], infos: []},
        {id: 'f2-c5-r9', users: [], type: [], name: [], infos: []},
        {id: 'f2-c5-r10', users: [], type: [], name: [], infos: []},
        {id: 'f2-c5-r11', users: [], type: [], name: [], infos: []},
        {id: 'f2-c5-r12', users: [], type: [], name: [], infos: []},
        {id: 'f2-c5-r13', users: [], type: [], name: [], infos: []},
        {id: 'f2-c5-r15', users: [], type: [], name: [], infos: []},
        {id: 'f2-c5-r16', users: [], type: [], name: [], infos: []},
        {id: 'f2-c6-r1', users: [], type: [], name: [], infos: []},
        {id: 'f2-c6-r2', users: [], type: [], name: [], infos: []},
        {id: 'f2-c6-r3', users: [], type: [], name: [], infos: []},
        {id: 'f2-c6-r4', users: [], type: [], name: [], infos: []},
        {id: 'f2-c6-r5', users: [], type: [], name: [], infos: []},
        {id: 'f2-c6-r6', users: [], type: [], name: [], infos: []},
        {id: 'f2-c6-r7', users: [], type: [], name: [], infos: []},
        {id: 'f2-c6-r8', users: [], type: [], name: [], infos: []},
        {id: 'f2-c6-r9', users: [], type: [], name: [], infos: []},
        {id: 'f2-c6-r10', users: [], type: [], name: [], infos: []},
        {id: 'f2-c6-r11', users: [], type: [], name: [], infos: []},
        {id: 'f2-c6-r12', users: [], type: [], name: [], infos: []},
        {id: 'f2-c6-r13', users: [], type: [], name: [], infos: []},
        {id: 'f2-c6-r15', users: [], type: [], name: [], infos: []},
        {id: 'f2-c6-r16', users: [], type: [], name: [], infos: []},

    ]
    return (
        <div className="main">
            <Row>
                <Col span={18} className="left">
                    <Floor floor={floor} setFloor={setFloor} setRoom={setRoom}/>
                    <Building floor={floor} building={buildingModel} rooms={rooms} setRoom={setRoom} room={room}/>
                </Col>
                <Col span={6} className="right">
                        {JSON.stringify(room)}
                </Col>
            </Row>


        </div>
    );
}

export default Main;
